In [2]:
import numpy as np
A = np.array([[56.0,0.0,4.4,68.0],
            [1.2,104.0,52.0,8.0],
            [1.8,135.0,99.0,0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [5]:
#sum of each column
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [6]:
#you take an 1x4 matrix and divide for and 3x4 matrix
#reshape is redundant , but is ok to write because is easy to understand what the matrix look like
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [13]:
#in python, if you add a matrix to a number, the number will became an 1xn matrix
#broadcasting to all values of the matrix
B = np.array([[1],[2],[3],[4]])
print('original: \n')
print(B)
print('\nafter: \n')
C = B + 100
print(C)

original: 

[[1]
 [2]
 [3]
 [4]]

after: 

[[101]
 [102]
 [103]
 [104]]


In [17]:
#other example, python will copy the 1xn matrix to a mxn matrix
D = np.array([[1,2,3],
              [4,5,6]])
E = np.array([100,200,300])
F = D + E
print(F)

[[101 202 303]
 [104 205 306]]


In [7]:
#must be the same line size
a = np.random.randn(4,3)
print(a)
b = np.random.randn(3,2)
print("\n")
print(b)
c = a + b
print("\n")
print(c)

[[ 0.06360574 -1.09888043 -0.5421843 ]
 [ 0.7985779  -0.18945007 -0.95862095]
 [-1.23275284 -0.06784134  0.21201358]
 [-0.08193854  1.14012681 -0.81612762]]


[[ 0.37160239  1.45424536]
 [-0.72749444 -0.3662136 ]
 [-0.09830033  0.12341781]]


ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [14]:
#must be the same line size
a = np.random.randn(12888,150)
#print(a)
b = np.random.randn(150,45)
print("\n")
#print(b)
c = np.dot(a,b)
print("\n")
print(c.shape)





(12888, 45)


In [15]:
a = np.random.rand(3,3)
b = np.random.randn(3,1)
c = a*b
print(c)

[[ 0.06178217  0.33429826  0.20745227]
 [-0.65113793 -0.820692   -0.57184322]
 [ 0.41690839  0.64575277  0.21327377]]
